### ISSUE TITLE
[client] 대화방 목록 페이지

### ISSUE THREAD

**Issue by karuiner** [karuiner/mini_side_project#13]
### ISSUE
 * Group : client
 * Type : feature
 * Detail :  대화방 카드 구성, 대화방 정보 요청 확인,  대화방 추가,  삭제
### TODO
- [x] 대화방 카드 구성
- [x] 대화방 정보 요청 확인
- [x] 대화방 추가 삭제 확인
### Estimated time
1.5h

**Comment by karuiner** [comment]
카드 구성, 정보 요청, 추가 부분 구현, 삭제는 채팅 방 설정 부분에서 다룰 예정
