### ISSUE TITLE
[server] 서버 기초 구성

### ISSUE THREAD

**Issue by karuiner** [karuiner/mini_side_project#2]
### ISSUE
 * Group :  server
 * Type :  featue
 * Detail :  서버 구성  각 api 루트 구성, db 생성, db schema 구성, db - 서버 연결
### TODO
- [x] db 구성 및 schema 생성
- [x] 서버 구성
- [x] api문서에서 주어진 path 생성
- [x] 각 path의 엔드 포인트 동작 여부 확인
### Estimated time
 3 h

**Comment by karuiner** [comment]
하지만 socket.io에 대한 사용법을 적용 시키지는 못하였다. 해당 사용법과 현재 형태와의 타협점을 찾아 적용 해봐야겠다.
