### ISSUE TITLE
[client] 랜딩 페이지, 로그인 window 제작

### ISSUE THREAD

**Issue by karuiner** [karuiner/mini_side_project#9]
### ISSUE
 * Group : client
 * Type : featue
 * Detail :  랜딩 페이지 생성, 로그인 window 제작, 메인 페이지로의  이동 확인
### TODO
- [x] 랜딩 페이지 생성
- [x] 로그인 window 제작
- [x] 메인 페이지로의  이동 확인
### Estimated time
1.5 h

**Comment by karuiner** [comment]
기본적인 구조를 잡고 단순한 동작만 가능한 목업을 구성하였다. 실제 서버 동작 방식도 오락가락 하고 클라이언트 정보 관리도 redux를 포함해야 할 것도 같고 영 정리가 되지 않은 상황이라 목업 수준에서 멈추었다.
